name: Setup

on:
  workflow_run:
    workflows:
      - Dependencies
    types:
      - completed

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
      - name: Clone compose using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            DOCKER_COMPOSE_FOLDER=$HOME/docker-compose.yml
            if [ ! -d $DOCKER_COMPOSE_FOLDER ]
            then
              git clone https://github.com/gabrielrufino/docker-compose.yml.git $DOCKER_COMPOSE_FOLDER
              cd $DOCKER_COMPOSE_FOLDER
            else
              cd $DOCKER_COMPOSE_FOLDER
              git pull
            fi
            cp .env.default .env
  firewall:
    runs-on: ubuntu-latest

    steps:
      - name: Setup firewall using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            ufw deny 3003
            ufw deny 16543
            ufw allow 22
            ufw allow 80
            ufw allow 443
            ufw enable
  traefik:
    runs-on: ubuntu-latest
    needs:
      - compose
      - firewall
    steps:
      - name: Setup traefik
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            # htpasswd -b -c /etc/nginx/.htpasswd root root
            cd $HOME/docker-compose.yml
            echo "TRAEFIK_BASE_HOST=workspeace.gabrielrufino.com" >> .env
            docker compose up traefik -d
