name: Setup

on:
  workflow_run:
    workflows:
      - Dependencies
    types:
      - completed

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Clone docker-compose using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            DOCKER_COMPOSE_FOLDER=$HOME/docker-compose.yml
            if [ ! -d $DOCKER_COMPOSE_FOLDER ]
            then
              git clone https://github.com/gabrielrufino/docker-compose.yml.git $DOCKER_COMPOSE_FOLDER
            else
              cd $DOCKER_COMPOSE_FOLDER
              git pull
            fi
  firewall:
    runs-on: ubuntu-latest

    steps:
      - name: Setup firewall using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            ufw deny 3003
            ufw deny 16543
            ufw allow 22
            ufw allow 'Nginx HTTP'
            ufw allow 'Nginx HTTPS'
            ufw enable
  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Setup nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            htpasswd -b -c /etc/nginx/.htpasswd root root
            cd /etc/nginx/sites-available
            wget https://raw.githubusercontent.com/gabrielrufino/workspeace/main/config/nginx/sites-available/default -O default
            systemctl restart nginx
            systemctl enable nginx
