name: Start

on:
  workflow_run:
    workflows:
      - Setup
    types:
      - completed
  workflow_dispatch:

jobs:
  vscode:
    runs-on: ubuntu-latest

    steps:
      - name: Start vscode using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd $HOME/docker-compose.yml
            docker compose up vscode -d
  pgadmin:
    runs-on: ubuntu-latest

    steps:
      - name: Start pgadmin using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd $HOME/docker-compose.yml
            docker compose up pgadmin -d
