name: Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: juliangruber/read-file-action@v1
        id: script
        with:
          path: ./scripts/update/server.sh
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: ${{ steps.script.outputs.content }}
  vscode:
    name: VSCode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: juliangruber/read-file-action@v1
        id: script
        with:
          path: ./scripts/update/vscode.sh
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: ${{ steps.script.outputs.content }}
