name: Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Update server using SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo apt update
            sudo apt upgrade -y
            sudo apt autoremove -y
  vscode:
    runs-on: ubuntu-latest

    steps:
      - name: Update vscode container using SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd $HOME/docker-compose.yml
            docker compose exec vscode sudo apt update
            docker compose exec vscode sudo apt upgrade -y 
            docker compose exec vscode sudo apt autoremove -y
